import { getCurrencySymbol } from "./Utils";

export const Currencies = [
  {
    key: 1,
    //value: "USD",
    value: 0,
    text: `${getCurrencySymbol("USD")} - US Dollar`,
  },
  {
    key: 2,
    //value: "CAD",
    value: 1,
    text: `${getCurrencySymbol("CAD")} - Canadian Dollar`,
  },
  {
    key: 3,
    //value: "JPY",
    value: 2,
    text: `${getCurrencySymbol("JPY")} - Japanese Yen`,
  },
  {
    key: 4,
    //value: "GBP",
    value: 3,
    text: `${getCurrencySymbol("GBP")} - Pound sterling`,
  },
  {
    key: 5,
    //value: "EUR",
    value: 4,
    text: `${getCurrencySymbol("EUR")} - Euro`,
  },
  {
    key: 6,
    //value: "HKD",
    value: 5,
    text: `${getCurrencySymbol("HKD")} - Hong Kong dollar`,
  },
  {
    key: 7,
    //value: "SGD",
    value: 6,
    text: `${getCurrencySymbol("SGD")} - Singapore dollar`,
  },
  {
    key: 8,
    //value: "TWD",
    value: 7,
    text: `${getCurrencySymbol("TWD")} - New Taiwan dollar`,
  },
  {
    key: 9,
    //value: "KRW",
    value: 8,
    text: `${getCurrencySymbol("KRW")} - South Korean won`,
  },
  {
    key: 10,
    //value: "AUD",
    value: 9,
    text: `${getCurrencySymbol("AUD")} - Australian dollar`,
  },
  {
    key: 11,
    //value: "NZD",
    value: 10,
    text: `${getCurrencySymbol("NZD")} - New Zealand dollar`,
  },
  {
    key: 12,
    //value: "INR",
    value: 11,
    text: `${getCurrencySymbol("INR")} - Indian Rupee`,
  },
  {
    key: 13,
    //value: "DKK",
    value: 12,
    text: `${getCurrencySymbol("DKK")} - Danish krone`,
  },
  {
    key: 14,
    //value: "NOK",
    value: 13,
    text: `${getCurrencySymbol("NOK")} - Norwegian krone`,
  },
  {
    key: 15,
    //value: "SEK",
    value: 14,
    text: `${getCurrencySymbol("SEK")} - Swedish krona`,
  },
  {
    key: 16,
    //value: "ILS",
    value: 15,
    text: `${getCurrencySymbol("ILS")} - Israeli new shekel`,
  },
  {
    key: 17,
    //value: "CNY",
    value: 16,
    text: `${getCurrencySymbol("CNY")} - Chinese Yuan (Renminbi)`,
  },
  {
    key: 18,
    //value: "PLN",
    value: 17,
    text: `${getCurrencySymbol("PLN")} - Polish Zloty`,
  },
  {
    key: 19,
    //value: "CHF",
    value: 18,
    text: `${getCurrencySymbol("CHF")} - Swiss Franc`,
  },
  {
    key: 20,
    //value: "CZK",
    value: 19,
    text: `${getCurrencySymbol("CZK")} - Czech Koruna`,
  },
  {
    key: 21,
    //value: "HUF",
    value: 20,
    text: `${getCurrencySymbol("HUF")} - Hungarian Forint`,
  },
  {
    key: 22,
    //value: "RON",
    value: 21,
    text: `${getCurrencySymbol("RON")} - Romanian Leu`,
  },
  {
    key: 23,
    //value: "ZAR",
    value: 22,
    text: `${getCurrencySymbol("ZAR")} - South African Rand`,
  },
  {
    key: 24,
    //value: "MYR",
    value: 23,
    text: `${getCurrencySymbol("MYR")} - Malaysian Ringgit`,
  },
  {
    key: 25,
    //value: "THB",
    value: 24,
    text: `${getCurrencySymbol("THB")} - Thai Baht`,
  },
  {
    key: 26,
    //value: "PHP",
    value: 25,
    text: `${getCurrencySymbol("PHP")} - Philippine peso`,
  },
];
