export const ParametricUnits = {
  None: { value: 0, name: 'None', icon: '', description: 'None', units: '' },
  Count: { value: 1, name: 'Count', icon: '', description: 'Quantity/count', units: 'count' },
  //
  Amp: { value: 2, name: 'Amp', icon: '', description: 'A', units: 'A', group: 'current' },
  Milliamp: { value: 3, name: 'Milliamp', icon: '', description: 'mA', units: 'mA', group: 'current' },
  Microamp: { value: 4, name: 'Microamp', icon: '', description: 'mA', units: 'µA', group: 'current' },
  Nanoamp: { value: 5, name: 'Nanoamp', icon: '', description: 'mA', units: 'nA', group: 'current' },
  Picoamp: { value: 6, name: 'Picoamp', icon: '', description: 'mA', units: 'pA', group: 'current' },
  Kiloamp: { value: 7, name: 'Kiloamp', icon: '', description: 'mA', units: 'kA', group: 'current' },
  Megaamp: { value: 8, name: 'Megaamp', icon: '', description: 'mA', units: 'MA', group: 'current' },
  Gigaamp: { value: 9, name: 'Gigaamp', icon: '', description: 'mA', units: 'GA', group: 'current' },

  Volt: { value: 10, name: 'Volt', icon: '', description: 'V', units: 'V', group: 'voltage' },
  Millivolt: { value: 11, name: 'Millivolt', icon: '', description: 'mV', units: 'mV', group: 'voltage' },
  Microvolt: { value: 12, name: 'Microvolt', icon: '', description: 'µV', units: 'µV', group: 'voltage' },
  Nanovolt: { value: 13, name: 'Nanovolt', icon: '', description: 'nV', units: 'nV', group: 'voltage' },
  Picovolt: { value: 14, name: 'Picovolt', icon: '', description: 'pV', units: 'pV', group: 'voltage' },
  Kilovolt: { value: 15, name: 'Kilovolt', icon: '', description: 'kV', units: 'kV', group: 'voltage' },
  Megavolt: { value: 16, name: 'Megavolt', icon: '', description: 'MV', units: 'MV', group: 'voltage' },
  Gigavolt: { value: 17, name: 'Gigavolt', icon: '', description: 'GV', units: 'GV', group: 'voltage' },

  Ohms: { value: 18, name: 'Ohms', icon: '', description: 'Ω', units: 'Ω' },
  Milliohm: { value: 19, name: 'Milliohm', icon: '', description: 'mΩ', units: 'mΩ', group: 'resistance' },
  Nanoohm: { value: 20, name: 'Nanoohm', icon: '', description: 'nΩ', units: 'nΩ', group: 'resistance' },
  Kiloohm: { value: 21, name: 'Kiloohm', icon: '', description: 'kΩ', units: 'kΩ', group: 'resistance' },
  Megaohm: { value: 22, name: 'Megaohm', icon: '', description: 'MΩ', units: 'MΩ', group: 'resistance' },
  Gigaohm: { value: 23, name: 'Gigaohm', icon: '', description: 'GΩ', units: 'GΩ', group: 'resistance' },
  Statohm: { value: 24, name: 'Statohm', icon: '', description: 'statΩ', units: 'statΩ', group: 'resistance' },
  Abaohm: { value: 25, name: 'Abaohm', icon: '', description: 'abΩ', units: 'abΩ', group: 'resistance' },

  Farad: { value: 26, name: 'Farad', icon: '', description: 'F', units: 'F', group: 'capacitance' },
  Microfarad: { value: 27, name: 'Microfarad', icon: '', description: 'µF', units: 'µF', group: 'capacitance' },
  Nanofarad: { value: 28, name: 'Nanofarad', icon: '', description: 'nF', units: 'nF', group: 'capacitance' },
  Picofarad: { value: 29, name: 'Picofarad', icon: '', description: 'pF', units: 'pF', group: 'capacitance' },
  Megafarad: { value: 30, name: 'Megafarad', icon: '', description: 'MF', units: 'MF', group: 'capacitance' },
  Gigafarad: { value: 31, name: 'Gigafarad', icon: '', description: 'GF', units: 'GF', group: 'capacitance' },
  Abfarad: { value: 32, name: 'Abfarad', icon: '', description: 'abF', units: 'abF', group: 'capacitance' },
  Statfarad: { value: 33, name: 'Statfarad', icon: '', description: 'statF', units: 'statF', group: 'capacitance' },

  Henry: { value: 34, name: 'Henry', icon: '', description: 'H', units: 'H', group: 'inductance' },
  Millihenry: { value: 35, name: 'Millihenry', icon: '', description: 'µH', units: 'µH', group: 'inductance' },
  Microhenry: { value: 36, name: 'Microhenry', icon: '', description: 'mH', units: 'mH', group: 'inductance' },
  Nanohenry: { value: 37, name: 'Nanohenry', icon: '', description: 'nH', units: 'nH', group: 'inductance' },
  Kilohenry: { value: 38, name: 'Kilohenry', icon: '', description: 'kH', units: 'kH', group: 'inductance' },
  Megahenry: { value: 39, name: 'Megahenry', icon: '', description: 'MH', units: 'MH', group: 'inductance' },
  Gigahenry: { value: 40, name: 'Gigahenry', icon: '', description: 'GH', units: 'GH', group: 'inductance' },

  Hertz: { value: 41, name: 'Hertz', icon: '', description: 'Hz', units: 'Hz', group: 'frequency' },
  Decahertz: { value: 42, name: 'Decahertz', icon: '', description: 'daHz', units: 'daHz', group: 'frequency' },
  Hectohertz: { value: 43, name: 'Hectohertz', icon: '', description: 'hHz', units: 'hHz', group: 'frequency' },
  Kilohertz: { value: 44, name: 'Kilohertz', icon: '', description: 'kHz', units: 'kHz', group: 'frequency' },
  Megahertz: { value: 45, name: 'Megahertz', icon: '', description: 'MHz', units: 'MHz', group: 'frequency' },
  Gigahertz: { value: 46, name: 'Gigahertz', icon: '', description: 'GHz', units: 'GHz', group: 'frequency' },
  Terahertz: { value: 47, name: 'Terahertz', icon: '', description: 'THz', units: 'THz', group: 'frequency' },
  Petahertz: { value: 48, name: 'Petahertz', icon: '', description: 'PHz', units: 'PHz', group: 'frequency' },

  TemperatureMetric: { value: 49, name: 'TemperatureMetric', icon: '', description: '°C', units: '°C', group: 'temperature' },
  TemperatureImperial: { value: 50, name: 'TemperatureImperial', icon: '', description: '°F', units: '°F', group: 'temperature' },
  TemperatureKelvin: { value: 51, name: 'TemperatureKelvin', icon: '', description: '°K', units: '°K', group: 'temperature' },
  TemperatureRankine: { value: 52, name: 'TemperatureRankine', icon: '', description: '°R', units: '°R', group: 'temperature' },
  TemperatureDelisle: { value: 53, name: 'TemperatureDelisle', icon: '', description: '°D', units: '°D', group: 'temperature' },
  TemperatureNewton: { value: 54, name: 'TemperatureNewton', icon: '', description: '°N', units: '°N', group: 'temperature' },
  TemperatureReaumur: { value: 55, name: 'TemperatureReaumur', icon: '', description: '°Ré', units: '°Ré', group: 'temperature' },
  TemperatureRomer: { value: 56, name: 'TemperatureRomer', icon: '', description: '°Rø', units: '°Rø', group: 'temperature' },

};