services:
  binner:
    container_name: Binner
    image: binnerofficial/binner:latest
    build:
      dockerfile: ./Dockerfile
    expose:
      - ${BINNER_PORT}
    restart: always
    ports:
      - ${BINNER_PORT}:${BINNER_PORT}
    volumes:
      - binner-config:/app/config
      - binner-db:/app/db
      - binner-certificates:/app/Certificates:ro
      - binner-logs:/app/logs:ro
volumes:
  binner-config:
    name: "Binner-Config"
  binner-db:
    name: "Binner-Database"
  binner-logs:
    name: "Binner-Logs"
  binner-certificates:
    name: "Binner-Certificates"
