services:
  binner:
    container_name: Binner
    image: binnerofficial/binner:test2
    restart: always
    environment:
      BINNER_USEHTTPS: true
      BINNER_PORT: 8090
      BINNER_PROVIDER: Binner
      BINNER_DB_FILENAME: /data/binner.db
    build:
      dockerfile: ./Dockerfile
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - C:\tmp\binnertest\config:/config
      - C:\tmp\binnertest\data:/data
      - C:\tmp\binnertest\certificates:/certificates
      - C:\tmp\binnertest\binner-logs:/logs
      - C:\tmp\binnertest\userfiles:/userfiles