services:
  binner:
    container_name: Binner
    image: binnerofficial/binner:latest
    restart: always
    environment:
      BINNER_PORT: 8090
      BINNER_PROVIDER: Binner
      BINNER_DB_FILENAME: ./binner.db
      BINNER_DB_HOST:
      BINNER_DB_PORT:
      BINNER_DB_USERNAME:
      BINNER_DB_PASSWORD:
      BINNER_DB_CONNECTIONSTRING:
    build:
      dockerfile: ./Dockerfile
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - binner-data:/data
      - binner-certificates:/Certificates:ro
      - binner-logs:/logs:ro
volumes:
  binner-data:
    name: "Binner-Data"
  binner-logs:
    name: "Binner-Logs"
  binner-certificates:
    name: "Binner-Certificates"
