services:
  binner:
    container_name: Binner
    image: binnerofficial/binner:latest
    restart: always
    environment:
      BINNER_USEHTTPS: true
      BINNER_PORT: 8090
      BINNER_PROVIDER: Binner
      BINNER_DB_FILENAME: /data/binner.db
    build:
      dockerfile: ./Dockerfile
    expose:
      - 8090
    ports:
      - 8090:8090
    volumes:
      - binner-config:/config
      - binner-data:/data
      - binner-userfiles:/userfiles
      - binner-certificates:/certificates
      - binner-logs:/logs
volumes:
  binner-config:
    name: "Binner-Config"
  binner-data:
    name: "Binner-Data"
  binner-userfiles:
    name: "Binner-UserFiles"
  binner-certificates:
    name: "Binner-Certificates"
  binner-logs:
    name: "Binner-Logs"
