// <auto-generated />
using System;
using Binner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Binner.Data.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(BinnerContext))]
    [Migration("20230411023437_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Binner.Data.Model.OAuthCredential", b =>
                {
                    b.Property<int>("OAuthCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OAuthCredentialId"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateExpiresUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OAuthCredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("OAuthCredentials");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthRequest", b =>
                {
                    b.Property<int>("OAuthRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OAuthRequestId"));

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AuthorizationReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReturnToUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OAuthRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("OAuthRequests");
                });

            modelBuilder.Entity("Binner.Data.Model.Part", b =>
                {
                    b.Property<long>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartId"));

                    b.Property<string>("ArrowPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BinNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BinNumber2")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DigiKeyPartNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keywords")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int");

                    b.Property<string>("LowestCostSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LowestCostSupplierUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MountingTypeId")
                        .HasColumnType("int");

                    b.Property<string>("MouserPartNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PackageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<long>("PartTypeId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<int?>("SwarmPartNumberManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PartId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("BinNumber", "UserId");

                    b.HasIndex("BinNumber2", "UserId");

                    b.HasIndex("Description", "UserId");

                    b.HasIndex("DigiKeyPartNumber", "UserId");

                    b.HasIndex("Keywords", "UserId");

                    b.HasIndex("Location", "UserId");

                    b.HasIndex("Manufacturer", "UserId");

                    b.HasIndex("ManufacturerPartNumber", "UserId");

                    b.HasIndex("MouserPartNumber", "UserId");

                    b.HasIndex("PartNumber", "UserId");

                    b.HasIndex("PartTypeId", "UserId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Binner.Data.Model.PartSupplier", b =>
                {
                    b.Property<long>("PartSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartSupplierId"));

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PartId")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("SupplierPartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PartSupplierId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("PartSuppliers");
                });

            modelBuilder.Entity("Binner.Data.Model.PartType", b =>
                {
                    b.Property<long>("PartTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartTypeId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ParentPartTypeId")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PartTypeId");

                    b.HasIndex("ParentPartTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId");

                    b.ToTable("PartTypes");
                });

            modelBuilder.Entity("Binner.Data.Model.Pcb", b =>
                {
                    b.Property<long>("PcbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PcbId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastSerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumberFormat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PcbId");

                    b.ToTable("Pcbs");
                });

            modelBuilder.Entity("Binner.Data.Model.PcbStoredFileAssignment", b =>
                {
                    b.Property<long>("PcbStoredFileAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PcbStoredFileAssignmentId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PcbId")
                        .HasColumnType("bigint");

                    b.Property<long>("StoredFileId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PcbStoredFileAssignmentId");

                    b.HasIndex("PcbId");

                    b.HasIndex("StoredFileId");

                    b.ToTable("PcbStoredFileAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.Project", b =>
                {
                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectId"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPartAssignment", b =>
                {
                    b.Property<long>("ProjectPartAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectPartAssignmentId"));

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PartId")
                        .HasColumnType("bigint");

                    b.Property<string>("PartName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PcbId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchematicReferenceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectPartAssignmentId");

                    b.HasIndex("PartId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectPartAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPcbAssignment", b =>
                {
                    b.Property<long>("ProjectPcbAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProjectPcbAssignmentId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<long>("PcbId")
                        .HasColumnType("bigint");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProjectPcbAssignmentId");

                    b.HasIndex("PcbId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectPcbAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.StoredFile", b =>
                {
                    b.Property<long>("StoredFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StoredFileId"));

                    b.Property<int>("Crc32")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("FileLength")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PartId")
                        .HasColumnType("bigint");

                    b.Property<int>("StoredFileType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StoredFileId");

                    b.HasIndex("PartId");

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("Binner.Data.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DateEmailConfirmedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastActiveUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLastLoginUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateLockedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EmailConfirmedIp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailSubscribed")
                        .HasColumnType("bit");

                    b.Property<long>("LastSetPasswordIp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("varbinary(max)");

                    b.Property<double?>("ReCaptchaScore")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.HasIndex("EmailAddress");

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Binner.Data.Model.UserIntegrationConfiguration", b =>
                {
                    b.Property<int>("UserIntegrationConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserIntegrationConfigurationId"));

                    b.Property<string>("ArrowApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArrowApiUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ArrowEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ArrowUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("DigiKeyApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigiKeyClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DigiKeyClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DigiKeyEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("DigiKeyOAuthPostbackUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouserApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouserCartApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MouserEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("MouserOrderApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MouserSearchApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OctopartClientId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OctopartClientSecret")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OctopartEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("SwarmApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwarmApiUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SwarmEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeSpan?>("SwarmTimeout")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserIntegrationConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserIntegrationConfigurations");
                });

            modelBuilder.Entity("Binner.Data.Model.UserLoginHistory", b =>
                {
                    b.Property<int>("UserLoginHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLoginHistoryId"));

                    b.Property<bool>("CanLogin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("ReCaptchaScore")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserLoginHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginHistory");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterConfiguration", b =>
                {
                    b.Property<int>("UserPrinterConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPrinterConfigurationId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("PartLabelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartLabelSource")
                        .HasColumnType("int");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RemoteAddressUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserPrinterConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPrinterConfigurations");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterTemplateConfiguration", b =>
                {
                    b.Property<int>("UserPrinterTemplateConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPrinterTemplateConfigurationId"));

                    b.Property<bool>("AutoSize")
                        .HasColumnType("bit");

                    b.Property<bool>("Barcode")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("FontName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<int>("Label")
                        .HasColumnType("int");

                    b.Property<int>("Line")
                        .HasColumnType("int");

                    b.Property<bool>("LowerCase")
                        .HasColumnType("bit");

                    b.Property<int>("MarginBottom")
                        .HasColumnType("int");

                    b.Property<int>("MarginLeft")
                        .HasColumnType("int");

                    b.Property<int>("MarginRight")
                        .HasColumnType("int");

                    b.Property<int>("MarginTop")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Rotate")
                        .HasColumnType("int");

                    b.Property<bool>("UpperCase")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserPrinterConfigurationId")
                        .HasColumnType("int");

                    b.HasKey("UserPrinterTemplateConfigurationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPrinterConfigurationId");

                    b.ToTable("UserPrinterTemplateConfigurations");
                });

            modelBuilder.Entity("Binner.Data.Model.UserToken", b =>
                {
                    b.Property<int>("UserTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserTokenId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DateExpiredUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DateRevokedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserToken");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthCredential", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("OAuthCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthRequest", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("OAuthRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.Part", b =>
                {
                    b.HasOne("Binner.Data.Model.PartType", "PartType")
                        .WithMany("Parts")
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("Parts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("Parts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartType");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.PartSupplier", b =>
                {
                    b.HasOne("Binner.Data.Model.Part", "Part")
                        .WithMany("PartSuppliers")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("PartSuppliers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.PartType", b =>
                {
                    b.HasOne("Binner.Data.Model.PartType", "ParentPartType")
                        .WithMany()
                        .HasForeignKey("ParentPartTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("PartTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentPartType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.PcbStoredFileAssignment", b =>
                {
                    b.HasOne("Binner.Data.Model.Pcb", "Pcb")
                        .WithMany("PcbStoredFileAssignments")
                        .HasForeignKey("PcbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.StoredFile", "StoredFile")
                        .WithMany("PcbStoredFileAssignments")
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pcb");

                    b.Navigation("StoredFile");
                });

            modelBuilder.Entity("Binner.Data.Model.Project", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPartAssignment", b =>
                {
                    b.HasOne("Binner.Data.Model.Part", "Part")
                        .WithMany("ProjectPartAssignments")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("ProjectPartAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPcbAssignment", b =>
                {
                    b.HasOne("Binner.Data.Model.Pcb", "Pcb")
                        .WithMany("ProjectPcbAssignments")
                        .HasForeignKey("PcbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("ProjectPcbAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pcb");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Binner.Data.Model.StoredFile", b =>
                {
                    b.HasOne("Binner.Data.Model.Part", "Part")
                        .WithMany("StoredFiles")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Part");
                });

            modelBuilder.Entity("Binner.Data.Model.UserIntegrationConfiguration", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserIntegrationConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserLoginHistory", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserLoginHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterConfiguration", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserPrinterConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterTemplateConfiguration", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserPrinterTemplateConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.UserPrinterConfiguration", "UserPrinterConfiguration")
                        .WithMany("UserPrinterTemplateConfigurations")
                        .HasForeignKey("UserPrinterConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserPrinterConfiguration");
                });

            modelBuilder.Entity("Binner.Data.Model.UserToken", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.Part", b =>
                {
                    b.Navigation("PartSuppliers");

                    b.Navigation("ProjectPartAssignments");

                    b.Navigation("StoredFiles");
                });

            modelBuilder.Entity("Binner.Data.Model.PartType", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Binner.Data.Model.Pcb", b =>
                {
                    b.Navigation("PcbStoredFileAssignments");

                    b.Navigation("ProjectPcbAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.Project", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("ProjectPartAssignments");

                    b.Navigation("ProjectPcbAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.StoredFile", b =>
                {
                    b.Navigation("PcbStoredFileAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.User", b =>
                {
                    b.Navigation("OAuthCredentials");

                    b.Navigation("OAuthRequests");

                    b.Navigation("PartSuppliers");

                    b.Navigation("PartTypes");

                    b.Navigation("Parts");

                    b.Navigation("Projects");

                    b.Navigation("UserIntegrationConfigurations");

                    b.Navigation("UserLoginHistory");

                    b.Navigation("UserPrinterConfigurations");

                    b.Navigation("UserPrinterTemplateConfigurations");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterConfiguration", b =>
                {
                    b.Navigation("UserPrinterTemplateConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
