// <auto-generated />
using System;
using Binner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Binner.Data.Migrations.Sqlite.Migrations
{
    [DbContext(typeof(BinnerContext))]
    partial class BinnerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Binner.Data.Model.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<bool>("IsPartLabelTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabelTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LabelId");

                    b.HasIndex("LabelTemplateId");

                    b.ToTable("Labels", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.LabelTemplate", b =>
                {
                    b.Property<int>("LabelTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dpi")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DriverHeight")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExtraData")
                        .HasColumnType("TEXT");

                    b.Property<string>("Height")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LabelCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LabelPaperSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Margin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Width")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LabelTemplateId");

                    b.ToTable("LabelTemplates", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthCredential", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccessToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateExpiresUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Provider");

                    b.HasIndex("UserId");

                    b.ToTable("OAuthCredentials", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthRequest", b =>
                {
                    b.Property<int>("OAuthRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorizationCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AuthorizationReceived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDescription")
                        .HasColumnType("TEXT");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnToUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OAuthRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("OAuthRequests", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("OrganizationId");

                    b.ToTable("Organizations", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.Part", b =>
                {
                    b.Property<long>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrowPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BinNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("BinNumber2")
                        .HasColumnType("TEXT");

                    b.Property<double>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("DatasheetUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigiKeyPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionValue1")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionValue2")
                        .HasColumnType("TEXT");

                    b.Property<string>("FootprintName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Keywords")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LowestCostSupplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("LowestCostSupplierUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("ManufacturerPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("MountingTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MouserPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("PartNumber")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("PartTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SymbolName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmePartNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("BinNumber", "UserId");

                    b.HasIndex("BinNumber2", "UserId");

                    b.HasIndex("Description", "UserId");

                    b.HasIndex("DigiKeyPartNumber", "UserId");

                    b.HasIndex("Keywords", "UserId");

                    b.HasIndex("Location", "UserId");

                    b.HasIndex("Manufacturer", "UserId");

                    b.HasIndex("ManufacturerPartNumber", "UserId");

                    b.HasIndex("MouserPartNumber", "UserId");

                    b.HasIndex("PartNumber", "UserId");

                    b.HasIndex("PartTypeId", "UserId");

                    b.ToTable("Parts", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.PartSupplier", b =>
                {
                    b.Property<long>("PartSupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumOrderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupplierPartNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartSupplierId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("PartSuppliers", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.PartType", b =>
                {
                    b.Property<long>("PartTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Icon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ParentPartTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartTypeId");

                    b.HasIndex("ParentPartTypeId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId");

                    b.ToTable("PartTypes", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.Pcb", b =>
                {
                    b.Property<long>("PcbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumberFormat")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PcbId");

                    b.HasIndex("UserId");

                    b.ToTable("Pcbs", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.PcbStoredFileAssignment", b =>
                {
                    b.Property<long>("PcbStoredFileAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PcbId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PcbStoredFileAssignmentId");

                    b.HasIndex("PcbId");

                    b.HasIndex("StoredFileId");

                    b.HasIndex("UserId");

                    b.ToTable("PcbStoredFileAssignments", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.Project", b =>
                {
                    b.Property<long>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Color")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId");

                    b.HasIndex("UserId");

                    b.HasIndex("Name", "UserId");

                    b.ToTable("Projects", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPartAssignment", b =>
                {
                    b.Property<long>("ProjectPartAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomDescription")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PcbId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchematicReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectPartAssignmentId");

                    b.HasIndex("PartId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectPartAssignments", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPcbAssignment", b =>
                {
                    b.Property<long>("ProjectPcbAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PcbId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectPcbAssignmentId");

                    b.HasIndex("PcbId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectPcbAssignments", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPcbProduceHistory", b =>
                {
                    b.Property<long>("ProjectPcbProduceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<double>("PcbCost")
                        .HasColumnType("REAL");

                    b.Property<long?>("PcbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PcbQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProjectProduceHistoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectPcbProduceHistoryId");

                    b.HasIndex("PcbId");

                    b.HasIndex("ProjectProduceHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectPcbProduceHistory", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectProduceHistory", b =>
                {
                    b.Property<long>("ProjectProduceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartsConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ProduceUnassociated")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectProduceHistoryId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectProduceHistory", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.StoredFile", b =>
                {
                    b.Property<long>("StoredFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Crc32")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("FileLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("RecordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecordType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoredFileType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StoredFileId");

                    b.HasIndex("PartId");

                    b.HasIndex("UserId");

                    b.ToTable("StoredFiles", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DateEmailConfirmedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastActiveUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLastLoginUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateLockedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("TEXT");

                    b.Property<long>("EmailConfirmedIp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEmailSubscribed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSetPasswordIp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<string>("LocaleCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocaleLanguage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfileImage")
                        .HasColumnType("BLOB");

                    b.Property<double?>("ReCaptchaScore")
                        .HasColumnType("REAL");

                    b.HasKey("UserId");

                    b.HasIndex("EmailAddress");

                    b.HasIndex("Name");

                    b.HasIndex("PhoneNumber");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.UserIntegrationConfiguration", b =>
                {
                    b.Property<int>("UserIntegrationConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrowApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrowApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ArrowEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArrowUsername")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("DigiKeyApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigiKeyClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DigiKeyClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DigiKeyEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DigiKeyOAuthPostbackUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MouserApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MouserCartApiKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MouserEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MouserOrderApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("MouserSearchApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("OctopartClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OctopartClientSecret")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OctopartEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SwarmApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SwarmApiUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SwarmEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("SwarmTimeout")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmeApiKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmeApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TmeApplicationSecret")
                        .HasColumnType("TEXT");

                    b.Property<string>("TmeCountry")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TmeEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserIntegrationConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserIntegrationConfigurations", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.UserLoginHistory", b =>
                {
                    b.Property<int>("UserLoginHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanLogin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ReCaptchaScore")
                        .HasColumnType("REAL");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserLoginHistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLoginHistory", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterConfiguration", b =>
                {
                    b.Property<int>("UserPrinterConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PartLabelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PartLabelSource")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrinterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteAddressUrl")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserPrinterConfigurationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserPrinterConfigurations", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterTemplateConfiguration", b =>
                {
                    b.Property<int>("UserPrinterTemplateConfigurationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Barcode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("FontName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Label")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Line")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LowerCase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginBottom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginLeft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginRight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MarginTop")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rotate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UpperCase")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserPrinterConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserPrinterTemplateConfigurationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserPrinterConfigurationId");

                    b.ToTable("UserPrinterTemplateConfigurations", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.UserToken", b =>
                {
                    b.Property<int>("UserTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreatedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DateExpiredUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModifiedUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<DateTime?>("DateRevokedUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("Ip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TokenTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("UserTokens", "dbo");
                });

            modelBuilder.Entity("Binner.Data.Model.Label", b =>
                {
                    b.HasOne("Binner.Data.Model.LabelTemplate", "LabelTemplate")
                        .WithMany("Labels")
                        .HasForeignKey("LabelTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LabelTemplate");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthCredential", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("OAuthCredentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.OAuthRequest", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("OAuthRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.Part", b =>
                {
                    b.HasOne("Binner.Data.Model.PartType", "PartType")
                        .WithMany("Parts")
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("Parts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("Parts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PartType");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.PartSupplier", b =>
                {
                    b.HasOne("Binner.Data.Model.Part", "Part")
                        .WithMany("PartSuppliers")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("PartSuppliers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.PartType", b =>
                {
                    b.HasOne("Binner.Data.Model.PartType", "ParentPartType")
                        .WithMany()
                        .HasForeignKey("ParentPartTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("PartTypes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ParentPartType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.Pcb", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("Pcbs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.PcbStoredFileAssignment", b =>
                {
                    b.HasOne("Binner.Data.Model.Pcb", "Pcb")
                        .WithMany("PcbStoredFileAssignments")
                        .HasForeignKey("PcbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.StoredFile", "StoredFile")
                        .WithMany("PcbStoredFileAssignments")
                        .HasForeignKey("StoredFileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("PcbStoredFileAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pcb");

                    b.Navigation("StoredFile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.Project", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPartAssignment", b =>
                {
                    b.HasOne("Binner.Data.Model.Part", "Part")
                        .WithMany("ProjectPartAssignments")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("ProjectPartAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("ProjectPartAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPcbAssignment", b =>
                {
                    b.HasOne("Binner.Data.Model.Pcb", "Pcb")
                        .WithMany("ProjectPcbAssignments")
                        .HasForeignKey("PcbId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("ProjectPcbAssignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("ProjectPcbAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pcb");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectPcbProduceHistory", b =>
                {
                    b.HasOne("Binner.Data.Model.Pcb", "Pcb")
                        .WithMany("ProjectPcbProduceHistory")
                        .HasForeignKey("PcbId");

                    b.HasOne("Binner.Data.Model.ProjectProduceHistory", "ProjectProduceHistory")
                        .WithMany("ProjectPcbProduceHistory")
                        .HasForeignKey("ProjectProduceHistoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("ProjectPcbProduceHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pcb");

                    b.Navigation("ProjectProduceHistory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectProduceHistory", b =>
                {
                    b.HasOne("Binner.Data.Model.Project", "Project")
                        .WithMany("ProjectProduceHistory")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("ProjectProduceHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.StoredFile", b =>
                {
                    b.HasOne("Binner.Data.Model.Part", "Part")
                        .WithMany("StoredFiles")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("StoredFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Part");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserIntegrationConfiguration", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserIntegrationConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserLoginHistory", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserLoginHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterConfiguration", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserPrinterConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterTemplateConfiguration", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserPrinterTemplateConfigurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Binner.Data.Model.UserPrinterConfiguration", "UserPrinterConfiguration")
                        .WithMany("UserPrinterTemplateConfigurations")
                        .HasForeignKey("UserPrinterConfigurationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserPrinterConfiguration");
                });

            modelBuilder.Entity("Binner.Data.Model.UserToken", b =>
                {
                    b.HasOne("Binner.Data.Model.User", "User")
                        .WithMany("UserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Binner.Data.Model.LabelTemplate", b =>
                {
                    b.Navigation("Labels");
                });

            modelBuilder.Entity("Binner.Data.Model.Part", b =>
                {
                    b.Navigation("PartSuppliers");

                    b.Navigation("ProjectPartAssignments");

                    b.Navigation("StoredFiles");
                });

            modelBuilder.Entity("Binner.Data.Model.PartType", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Binner.Data.Model.Pcb", b =>
                {
                    b.Navigation("PcbStoredFileAssignments");

                    b.Navigation("ProjectPcbAssignments");

                    b.Navigation("ProjectPcbProduceHistory");
                });

            modelBuilder.Entity("Binner.Data.Model.Project", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("ProjectPartAssignments");

                    b.Navigation("ProjectPcbAssignments");

                    b.Navigation("ProjectProduceHistory");
                });

            modelBuilder.Entity("Binner.Data.Model.ProjectProduceHistory", b =>
                {
                    b.Navigation("ProjectPcbProduceHistory");
                });

            modelBuilder.Entity("Binner.Data.Model.StoredFile", b =>
                {
                    b.Navigation("PcbStoredFileAssignments");
                });

            modelBuilder.Entity("Binner.Data.Model.User", b =>
                {
                    b.Navigation("OAuthCredentials");

                    b.Navigation("OAuthRequests");

                    b.Navigation("PartSuppliers");

                    b.Navigation("PartTypes");

                    b.Navigation("Parts");

                    b.Navigation("PcbStoredFileAssignments");

                    b.Navigation("Pcbs");

                    b.Navigation("ProjectPartAssignments");

                    b.Navigation("ProjectPcbAssignments");

                    b.Navigation("ProjectPcbProduceHistory");

                    b.Navigation("ProjectProduceHistory");

                    b.Navigation("Projects");

                    b.Navigation("StoredFiles");

                    b.Navigation("UserIntegrationConfigurations");

                    b.Navigation("UserLoginHistory");

                    b.Navigation("UserPrinterConfigurations");

                    b.Navigation("UserPrinterTemplateConfigurations");

                    b.Navigation("UserTokens");
                });

            modelBuilder.Entity("Binner.Data.Model.UserPrinterConfiguration", b =>
                {
                    b.Navigation("UserPrinterTemplateConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
